development:
  hosts:
    - my-cassandra 
  port: 9042
  keyspace: my_keyspace_dev
  replication:
    class: SimpleStrategy
    replication_factor: 1

test:
  hosts:
    - my-cassandra
  port: 9042
  keyspace: cassandra_migrations_test
  replication:
    class: 'SimpleStrategy'
    replication_factor: 1

production:
  hosts:
    - 'cass1.my_app.biz'
    - 'cass2.my_app.biz'
    - 'cass3.my_app.biz'
  port: 9042
  keyspace: cassandra_migrations_production
  username: myappuser
  password: password1
  replication:
    class: NetworkTopologyStrategy
    datacenter1: 3
    datacenter2: 2
