# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e53c18a9870364b99a67a16e22fa287a98aa6dc13b718a1379a34d9eeba7ed1a9d24e3345de73a487a4d2de984f883d98314cfcd93563bfa3a08ec2a6a2bbe7d

test:
  secret_key_base: 83705b5c95ba763ce40f8760f1c210be642843bd8b32a7000a4c5b80267ed72dc7f09f9875a407dcc8c42ccd73f59a9c68e345a16d588920ab89b876619dda85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
