version: '2'
services:
 cassandra:
    image: cassandra
    volumes:
     - /usr/local/lib/cassandra:/var/lib/cassandra
    container_name: my-cassandra
    mem_limit: 1G
 mybot:
    image: mybot:dev
    container_name: mybot
    ports: 
     - "8080:8080" 
    depends_on:
     - cassandra
 myweb:
    image: myweb:dev
    container_name: myweb
    ports: 
     - "3000:3000"
