version: '2'
services:
  cassandra-1:
    image: cassandra
    container_name: cassandra-1
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-1"
    ports:
    - 7000
    volumes:
      - "cassandra-vol1:/var/lib/cassandra"
    restart: always
  cassandra-2:
    image: cassandra
    container_name: cassandra-2
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-2"
      CASSANDRA_SEEDS: "cassandra-1"
    ports:
    - 7000
    depends_on:
      - cassandra-1
    volumes:
      - "cassandra-vol2:/var/lib/cassandra"
    restart: always

volumes:
  cassandra-vol1:
    external:
      name: myvol1
  cassandra-vol2:
    external:
      name: myvol2

networks:
  default:
    external:
       name: overlay-net
